### ISSUE TITLE
ImportError: cannot import name 'hparam_pb2' from 'model_search.proto' (unknown location)

### ISSUE THREAD

**Issue by dghlnvyps** [google/model_search#15]
>>> from model_search import oss_trainer_lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\src\model_search\model_search\oss_trainer_lib.py", line 28, in <module>
    from model_search import hparam as hp
  File "E:\src\model_search\model_search\hparam.py", line 26, in <module>
    from model_search.proto import hparam_pb2
ImportError: cannot import name 'hparam_pb2' from 'model_search.proto' (unknown location)

**Comment by erimyanik** [comment]
Same here.

**Comment by erimyanik** [comment]
You may wanna refer to this --> https://github.com/google/model_search/issues/3
