### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 100: invalid continuation byte

### ISSUE THREAD

**Issue by dghlnvyps** [google/model_search#16]
I run the demo test.py:

import model_search
from model_search import constants
from model_search import single_trainer
from model_search.data import csv_data

trainer = single_trainer.SingleTrainer(
    data=csv_data.Provider(
        label_index=0,
        logits_dimension=2,
        record_defaults=[0, 0, 0, 0],
        filename="model_search/data/testdata/csv_random_data.csv"),
    spec=constants.DEFAULT_DNN)

trainer.try_models(
    number_models=200,
    train_steps=1000,
    eval_steps=100,
    root_dir="/tmp/run_example",
    batch_size=32,
    experiment_name="example",
    experiment_owner="model_search_user")

but there is an error and I can't find the reason. The error informations is:

(gpu) E:\src\model_search>python test.py
2021-02-23 16:24:06.170523: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-02-23 16:24:06.175639: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    spec=constants.DEFAULT_DNN)
  File "E:\src\model_search\model_search\single_trainer.py", line 33, in __init__
    text_format.Parse(f.read(), self._spec)
  File "d:\Documents\Application Data\Python\Python37\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
    self._preread_check()
  File "d:\Documents\Application Data\Python\Python37\site-packages\tensorflow\python\lib\io\file_io.py", line 79, in _preread_check
    self.__name, 1024 * 512)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 100: invalid continuation byte

**Comment by hadehuang** [comment]
I have the same issue. How to fix it ?

**Comment by Mrmdzz** [comment]
The same problem, top up

**Comment by hadehuang** [comment]
I have fixed the problem, please refer the link:
https://github.com/tensorflow/tensorflow/issues/37924

**Comment by LJingnan** [comment]
I fixed this issue:
try to print constants.DEFAULT_DNN
and you will find this path is wrong, just change this
