### ISSUE TITLE
Can't fine module : ModuleNotFoundError: No module named 'ml_metadata'

### ISSUE THREAD

**Issue by KevinRyu** [google/model_search#28]
Hello,

Well... I can't find ml_metadata module or package anywhere.
What is weird thing is... I didn't get this error in other PC. (It might have different python version and environment)
Anyway, where is ml_metadata module? Is this no problem??? 
Please advise as necessary.

=================== Error message ===================================================

(modelsch) PS D:\PROGRAMMING\model_search> python ms.py
2021-02-27 07:05:53.471047: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "ms.py", line 3, in <module>
    from model_search import single_trainer
  File "D:\PROGRAMMING\model_search\model_search\single_trainer.py", line 17, in <module>
    from model_search import oss_trainer_lib
  File "D:\PROGRAMMING\model_search\model_search\oss_trainer_lib.py", line 29, in <module>
    from model_search import phoenix
  File "D:\PROGRAMMING\model_search\model_search\phoenix.py", line 33, in <module>
    from model_search.metadata import ml_metadata_db
  File "D:\PROGRAMMING\model_search\model_search\metadata\ml_metadata_db.py", line 24, in <module>
    from ml_metadata import metadata_store
ModuleNotFoundError: No module named 'ml_metadata'

**Comment by KevinRyu** [comment]
Dose anybody else having this issue? Is this a problem only for me?

**Comment by davidxiaozhi** [comment]
You should first convert the probuf file to the corresponding Python file
 protoc --python_out=./ model_search/proto/phoenix_spec.proto
 protoc --python_out=./ model_search/proto/hparam.proto
 protoc --python_out=./ model_search/proto/distillation_spec.proto
 protoc --python_out=./ model_search/proto/ensembling_spec.proto
 protoc --python_out=./ model_search/proto/transfer_learning_spec.proto

**Comment by KevinRyu** [comment]
> You should first convert the probuf file to the corresponding Python file
> protoc --python_out=./ model_search/proto/phoenix_spec.proto
> protoc --python_out=./ model_search/proto/hparam.proto
> protoc --python_out=./ model_search/proto/distillation_spec.proto
> protoc --python_out=./ model_search/proto/ensembling_spec.proto
> protoc --python_out=./ model_search/proto/transfer_learning_spec.proto

Thanks. But I already made those files by using protoc compiler. But I will check missing file again.

**Comment by KevinRyu** [comment]
> You should first convert the probuf file to the corresponding Python file
> protoc --python_out=./ model_search/proto/phoenix_spec.proto
> protoc --python_out=./ model_search/proto/hparam.proto
> protoc --python_out=./ model_search/proto/distillation_spec.proto
> protoc --python_out=./ model_search/proto/ensembling_spec.proto
> protoc --python_out=./ model_search/proto/transfer_learning_spec.pro

All python files are already exists. Although I rebuilt all files and ran .. But problem is not solved. Anyway, thanks a lot.

**Comment by davidxiaozhi** [comment]
ModuleNotFoundError: No module named 'ml_metadata'

If you are running from source code, this is likely due to the location of your Python script. It is recommended that you run it in the same directory as  README.md

**Comment by joelma1** [comment]
have you tried installing the module? 
pip install ml-metadata

**Comment by KevinRyu** [comment]
> have you tried installing the module?
> pip install ml-metadata

Thank you very much. I installed by using pip. It was solved.
